# Site settings
title: "Transassy"
email:
description: "Blog della pagina Facebook Transassy"
baseurl: "https://transassy.github.io"
url: "https://transassy.github.io"
title_description: "Blog della pagina Facebook Transassy. Qui si parla di temi trans e si denuncia ogni tipo di transfobia, reazionari e reazionarie state alla larga! ♥ Potete contattarci inviando un messaggio privato alla pagina."
title_image: "https://avatars.githubusercontent.com/u/85081927"
google_analytics:
disqus_account:
github_repository: https://github.com/Transassy/transassy.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username:
github_username: transassy
instagram_username: 
reddit_username: 
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link: https://www.facebook.com/transassy

# Footer
footer_left: "Tema di <a href=\"https://github.com/jacobtomlinson/carte-noire\">Jacob Tomlinson</a>"
footer_right: "Codice su <a href=\"https://github.com/Transassy/transassy.github.io\">Github</a> &nbsp;<i class=\"fab fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
